apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "22 1 * * *"
  jobTemplate:
    spec:
      metadata:
        name: job-spec
      conditions: 3
      parallelism: 3
      template:
        spec:
          containers:
          - name: job
            image: nginx
          restartPolicy: Never
